In [1]:
import numpy as np

In [3]:
list=np.random.randint(3,10,20)

In [4]:
np.mean(list)

5.85

In [5]:
list

array([9, 8, 4, 4, 5, 6, 6, 8, 7, 7, 4, 6, 9, 6, 3, 4, 3, 5, 8, 5])

In [6]:
list=np.random.randint(3,10,20)

In [7]:
np.median(list)

5.5

In [8]:
import statistics as st

In [9]:
list=np.random.randint(3,10,20)

In [11]:
st.mode(list)

9

In [12]:
list

array([5, 4, 3, 7, 8, 5, 3, 9, 6, 8, 9, 9, 8, 5, 3, 9, 7, 5, 9, 6])

In [58]:
import pandas as pd

In [59]:
data=pd.read_csv(r'C:\study materials\data science\pandas\stock_data.csv')

In [60]:
data

Date   Open   High    Low  Close    Volume   Name
0       1/3/2006  39.69  41.22  38.79  40.91  24232729   AABA
1       1/4/2006  41.22  41.90  40.77  40.97  20553479   AABA
2       1/5/2006  40.93  41.73  40.85  41.53  12829610   AABA
3       1/6/2006  42.88  43.57  42.80  43.21  29422828   alex
4       1/9/2006  43.10  43.66  42.82  43.42  16268338  queen
...          ...    ...    ...    ...    ...       ...    ...
3014  12/22/2017  71.42  71.87  71.22  71.58  10979165   AABA
3015  12/26/2017  70.94  71.39  69.63  69.86   8542802   AABA
3016  12/27/2017  69.77  70.49  69.69  70.06   6345124   AABA
3017  12/28/2017  70.12  70.32  69.51  69.82   7556877   AABA
3018  12/29/2017  69.79  70.13  69.43  69.85   6613070   AABA

[3019 rows x 7 columns]

In [61]:
np.mean(data["Close"])

28.412726068234516

In [62]:
np.median(Closdata["e"])

27.1

In [63]:
st.mode(data["Close"])

15.1

In [64]:
data=np.array([4,5,5,5,5,6,6,6,6,7,7,7,7,8])

In [65]:
range=data.max()-data.min()

In [66]:
print(range)

4


In [67]:
dataxyz=data["Close"].max()-data["Close"].min()

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [68]:
print(dataxyz)

63.980000000000004


In [92]:
data=pd.read_csv(r'C:\study materials\data science\pandas\weather2.csv')

In [93]:
data

Day      City  Temperature  WindSpeed   event
0    1/1/2017  new work           30          6    rain
1    1/2/2017  new work           36          7   sunny
2    1/3/2017  new work           28         12    snow
3   1/4/20017  new work           33          7   sunny
4    1/1/2017    mumbai           90          5   sunny
5    1/2/2017    mumbai           85         12     fog
6    1/3/2017    mumbai           87         15     fog
7    1/4/2017    mumbai           92          5    rain
8    1/1/2017    paries           45         20   sunny
9    1/2/2017    paries           50         13  cloudy
10   1/3/2017    paries           54          8  cloudy
11   1/4/2017    paries           42         10  cloudy

In [71]:
data=np.array([4,5,5,5,6,6,6,6,7,7,7,8])

In [72]:
q1=np.percentile(data,25)

In [73]:
q2=np.percentile(data,50)

In [74]:
q3=np.percentile(data,75)

In [75]:
IQR=q3-q1

In [76]:
print(IQR)

2.0


In [94]:
(data["Temperature"])

0     30
1     36
2     28
3     33
4     90
5     85
6     87
7     92
8     45
9     50
10    54
11    42
Name: Temperature, dtype: int64

In [78]:
data

array([4, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 8])

In [83]:
(data["Temperature"])

0     30
1     36
2     28
3     33
4     90
5     85
6     87
7     92
8     45
9     50
10    54
11    42
Name: Temperature, dtype: int64

In [80]:
data

array([4, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 8])

In [86]:
data=np.array([20,36,28,33,10,85,15,18,45,50,54,42])

In [87]:
q1=np.percentile(data,25)

In [88]:
q2=np.percentile(data,50)

In [89]:
q3=np.percentile(data,75)

In [90]:
IQR=q3-q1

In [91]:
print(IQR)

26.75


In [95]:
q1=np.percentile(data["Temperature"],25)

In [96]:
q2=np.percentile(data["Temperature"],50)

In [97]:
q3=np.percentile(data["Temperature"],75)

In [98]:
IQR=q3-q1

In [99]:
print(IQR)

50.25
